### ISSUE TITLE
Require to separate a Tin Mine

### ISSUE THREAD

**Issue by RouterXdd** [AForgetfulness/TowerDefense#1]
Tin mine creates a coal or tin and this creates a problems with production
![image](https://github.com/AForgetfulness/TowerDefense/assets/91018607/343169d0-5019-4c8f-93e1-1d04fabcb201)
Just make the Coal mine and remove coal generation from Tin mine

**Comment by AForgetfulness** [comment]
Hi, ok thx, i will make Coal mine and change this. Also you can use sorters from sector called "Abandoned Factory".  :D
